### ISSUE TITLE
event is not working (selected)="onSelected($event)"

### ISSUE THREAD

**Issue by dolyGD** [basvandenberg/angular2-select-demo#3]
<ng-select
                                        #singleSelectComponent
                                        [options]="hederListDropDown"
                                        [placeholder]="senderIDPlaceHolder"
                                        [allowClear]="canClearSelect"
                                        (opened)="onSelectOpened()"
                                        (closed)="onSelectClosed()"
                                        (selected)="onSingleSelected($event)"
                                        (deselected)="onSingleDeselected($event)"
                                        (change)="test1()"
                                        theme="classic">
                                    </ng-select>

but event not working

**Comment by basvandenberg** [comment]
Updated to the latest angular-select release. Should work now.
